### ISSUE TITLE
stopping

### ISSUE THREAD

**Issue by Ahmed748-hub** [Ahlyab/UCF#1]
it stops on click

**Comment by Ahlyab** [comment]
Hi @Ahmed748-hub , when you launch the program and if you click on the console while it's fetching coupons for you. Surely it will get stuck, you can just press any key like any arrow key to make it unstuck. it's a typical behavior of console applications. If this is not the issue you are facing then please briefly explain what error you are getting.

To double check if everything is working, I just downloaded a fresh copy and ran it. It is working well. 

looking forward to hear from you.
regards,
